# Site settings
title: Joshua J Harris
header-img: img/home-bg.jpg
email: joshua.jharris13@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
url: "localhost"
twitter_username: Joshua_J_Harris
github_username:  joshuajharris
linkedin_username: joshuajh

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
gems: [jekyll-paginate]
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
